version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: cpen321-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
      restart: always
      container_name: cpen321-app
      environment:
        - MONGODB_URI = ${MONGODB_URI}
        - PORT = ${PORT}

      ports:
        - ${PORT}:${PORT}
      depends_on:
        - mongo
      command: npm start

    

volumes:
  mongodb_data:

