# ~/app/docker-compose.yml
services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    env_file: .env
    command: ["--replSet", "rs0", "--bind_ip_all"]  # single-node replica set (enables transactions/change streams)
    volumes:
      - /opt/mongo/data:/data/db
      - /opt/mongo/init:/docker-entrypoint-initdb.d
    networks: [ appnet ]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    env_file: .env
    environment:
      # Compose service name "mongo" resolves via DNS to the mongo container
      MONGODB_URI: mongodb://admin:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${APP_DB_NAME}?authSource=admin&replicaSet=rs0
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    networks: [ appnet ]

networks:
  appnet:
    driver: bridge
